### PR TITLE
Listeners priority

### PR DESCRIPTION
**Pull request by fntlnz**
Implementation of listeners priority using `SplPriorityQueue`

### CODE REVIEW

**Comment by gianarb** [comment]
Perfect! In the future we can try to receive the `SplPriorityQueue` from `__construct` for example to use another implementation.. (I'm thinking https://github.com/ezimuel/FastPriorityQueue by @ezimuel :) )
https://github.com/gianarb/fast-event-manager/pull/6/files#diff-bffc1bf8e7d1e810e0e0f15672212ec3R14

**Comment by fntlnz** [comment]
We could define an interface and write down a few adaters using different priority queues. At some point one could write an adapter for RabbitMQ btw!

**Comment by gianarb** [comment]
ahah maybe at the moment it has a different priority! :P eheh..

**Comment by gianarb** [comment]
Thanks fa24a9a

**Pull request closed without merging**
